version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore: "
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore: "
    # Ignore dependabot PRs for VSCode and Node bumps,
    # since we want to control what version of VSCode we support,
    # and the Node version is tied to the VSCode version.
    ignore:
      - dependency-name: "@types/node"
      - dependency-name: "@types/vscode"
